import { FormDraft, FormReceived, FormSent } from "@/types/dashboard/components/forms-dashboard";

const receivedFormData: FormReceived[] = [
    { id: 1, formName: "Art Enthusiast form", receivedFrom: "Lead Design Org", status: "Active", dateReceived: "01-07-2025" },
    { id: 2, formName: "UI/UX Design Form", receivedFrom: "Hr Onboarding Team +1", status: "Closed", dateReceived: "02-07-2025" },
    { id: 3, formName: "Art Enthusiast Form", receivedFrom: "John@example.com", status: "Active", dateReceived: "03-07-2025" },
    {
        id: 4,
        formName: "Business Development Form",
        receivedFrom: "Marketing Strategies Org",
        status: "Active",
        dateReceived: "04-07-2025",
    },
    {
        id: 5,
        formName: "Marketing Strategy Form",
        receivedFrom: "Sales Development Team",
        status: "Closed",
        dateReceived: "05-07-2025",
    },
    {
        id: 6,
        formName: "Sales Performance Review",
        receivedFrom: "John@example.com",
        status: "Active",
        dateReceived: "06-07-2025",
    },
    {
        id: 7,
        formName: "Customer Feedback Survey",
        receivedFrom: "Customer Support Team",
        status: "Active",
        dateReceived: "12-07-2025",
    },
    {
        id: 8,
        formName: "Project Management Checklist",
        receivedFrom: "Product Development Team",
        status: "Active",
        dateReceived: "08-07-2025",
    },
    {
        id: 9,
        formName: "Financial Analysis Report",
        receivedFrom: "John@example.com",
        status: "Active",
        dateReceived: "09-07-2025",
    },
    {
        id: 10,
        formName: "Product Launch Plan",
        receivedFrom: "User Experience Team",
        status: "Active",
        dateReceived: "07-07-2025",
    },
    {
        id: 11,
        formName: "User Experience Research",
        receivedFrom: "John@example.com",
        status: "Closed",
        dateReceived: "10-07-2025",
    },
    {
        id: 12,
        formName: "Team Collaboration Agenda",
        receivedFrom: "Data Analysis Team",
        status: "Active",
        dateReceived: "11-07-2025",
    },
    {
        id: 13,
        formName: "Risk Assessment Template",
        receivedFrom: "Hr, Dinesh Mehta",
        status: "Closed",
        dateReceived: "11-07-2025",
    },
    {
        id: 14,
        formName: "Training Program Evaluation",
        receivedFrom: "Mahesh Dinkar",
        status: "Active",
        dateReceived: "11-08-2025",
    },
    {
        id: 15,
        formName: "Market Research Summary",
        receivedFrom: "Quality Assurance Team +1",
        status: "Closed",
        dateReceived: "11-09-2025",
    },
    {
        id: 16,
        formName: "Vendor Evaluation Form",
        receivedFrom: "Social Media Team + 1",
        status: "Active",
        dateReceived: "11-10-2025",
    },
    {
        id: 17,
        formName: "Client Onboarding Checklist",
        receivedFrom: "IT Support Team",
        status: "Closed",
        dateReceived: "16-07-2025",
    },
    {
        id: 18,
        formName: "Social Media Strategy Outline",
        receivedFrom: "Business Intelligence Team",
        status: "Closed",
        dateReceived: "11-12-2025",
    },
]

const sentFormData: FormSent[] = [
    { id: 1, formName: "Art Enthusiast form", sentTo: "Lead Design Org", status: "Active", dateSent: "01-07-2025" },
    { id: 2, formName: "UI/UX Design Form", sentTo: "Hr Onboarding Team +1", status: "Closed", dateSent: "02-07-2025" },
    { id: 3, formName: "Art Enthusiast Form", sentTo: "John@example.com", status: "Active", dateSent: "03-07-2025" },
    {
        id: 4,
        formName: "Business Development Form",
        sentTo: "Marketing Strategies Org",
        status: "Active",
        dateSent: "04-07-2025",
    },
    {
        id: 5,
        formName: "Marketing Strategy Form",
        sentTo: "Sales Development Team",
        status: "Closed",
        dateSent: "05-07-2025",
    },
    {
        id: 6,
        formName: "Sales Performance Review",
        sentTo: "John@example.com",
        status: "Active",
        dateSent: "06-07-2025",
    },
    {
        id: 7,
        formName: "Customer Feedback Survey",
        sentTo: "Customer Support Team",
        status: "Active",
        dateSent: "12-07-2025",
    },
    {
        id: 8,
        formName: "Project Management Checklist",
        sentTo: "Product Development Team",
        status: "Active",
        dateSent: "08-07-2025",
    },
    {
        id: 9,
        formName: "Financial Analysis Report",
        sentTo: "John@example.com",
        status: "Active",
        dateSent: "09-07-2025",
    },
    {
        id: 10,
        formName: "Product Launch Plan",
        sentTo: "User Experience Team",
        status: "Active",
        dateSent: "07-07-2025",
    },
    {
        id: 11,
        formName: "User Experience Research",
        sentTo: "John@example.com",
        status: "Closed",
        dateSent: "10-07-2025",
    },
    {
        id: 12,
        formName: "Team Collaboration Agenda",
        sentTo: "Data Analysis Team",
        status: "Active",
        dateSent: "11-07-2025",
    },
    {
        id: 13,
        formName: "Risk Assessment Template",
        sentTo: "Hr, Dinesh Mehta",
        status: "Closed",
        dateSent: "11-07-2025",
    },
    {
        id: 14,
        formName: "Training Program Evaluation",
        sentTo: "Mahesh Dinkar",
        status: "Active",
        dateSent: "11-08-2025",
    },
    {
        id: 15,
        formName: "Market Research Summary",
        sentTo: "Quality Assurance Team +1",
        status: "Closed",
        dateSent: "11-09-2025",
    },
    {
        id: 16,
        formName: "Vendor Evaluation Form",
        sentTo: "Social Media Team + 1",
        status: "Active",
        dateSent: "11-10-2025",
    },
    {
        id: 17,
        formName: "Client Onboarding Checklist",
        sentTo: "IT Support Team",
        status: "Closed",
        dateSent: "16-07-2025",
    },
    {
        id: 18,
        formName: "Social Media Strategy Outline",
        sentTo: "Business Intelligence Team",
        status: "Closed",
        dateSent: "11-12-2025",
    },
]
const draftFormData: FormDraft[] = [
    { id: 1, formName: "Art Enthusiast form", draftDate: "01-07-2025" },
    { id: 2, formName: "UI/UX Design Form", draftDate: "02-07-2025" },
    { id: 3, formName: "Art Enthusiast Form", draftDate: "03-07-2025" },
    {
        id: 4,
        formName: "Business Development Form",
        draftDate: "04-07-2025",
    },
    {
        id: 5,
        formName: "Marketing Strategy Form",
        draftDate: "05-07-2025",
    },
    {
        id: 6,
        formName: "Sales Performance Review",
        draftDate: "06-07-2025",
    },
    {
        id: 7,
        formName: "Customer Feedback Survey",
        draftDate: "12-07-2025",
    },
    {
        id: 8,
        formName: "Project Management Checklist",
        draftDate: "08-07-2025",
    },
    {
        id: 9,
        formName: "Financial Analysis Report",
        draftDate: "09-07-2025",
    },
    {
        id: 10,
        formName: "Product Launch Plan",
        draftDate: "07-07-2025",
    },
    {
        id: 11,
        formName: "User Experience Research",
        draftDate: "10-07-2025",
    },
    {
        id: 12,
        formName: "Team Collaboration Agenda",
        draftDate: "11-07-2025",
    },
    {
        id: 13,
        formName: "Risk Assessment Template",
        draftDate: "11-07-2025",
    },
    {
        id: 14,
        formName: "Training Program Evaluation",
        draftDate: "11-08-2025",
    },
    {
        id: 15,
        formName: "Market Research Summary",
        draftDate: "11-09-2025",
    },
    {
        id: 16,
        formName: "Vendor Evaluation Form",
        draftDate: "11-10-2025",
    },
    {
        id: 17,
        formName: "Client Onboarding Checklist",
        draftDate: "16-07-2025",
    },
    {
        id: 18,
        formName: "Social Media Strategy Outline",
        draftDate: "11-12-2025",
    },
]
export { receivedFormData, sentFormData, draftFormData }