/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export interface Answer {
  /** The question text */
  question: string;
  /** The submitted answer */
  answer: string;
  /** ID of the field */
  fieldId: string;
}
