/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { FieldQuestion } from "./fieldQuestion";
import type { ResultOption } from "./resultOption";
import type { ChoiceMeta } from "./choiceMeta";

export interface ChoiceQuestionResponse {
  field?: FieldQuestion;
  results?: ResultOption[];
  meta?: ChoiceMeta;
}
