/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type DeleteFormImageRequestImage =
  (typeof DeleteFormImageRequestImage)[keyof typeof DeleteFormImageRequestImage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeleteFormImageRequestImage = {
  cover: "cover",
  logo: "logo",
} as const;
