/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { Entry } from "./entry";
import type { Meta } from "./meta";

export interface EntriesResponse {
  /** List of entries */
  entries: Entry[];
  meta: Meta;
}
