/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { Field } from "./field";
import type { Result } from "./result";
import type { Meta } from "./meta";

export interface FieldResultsResponse {
  field: Field;
  /** Results for each option */
  results: Result[];
  meta: Meta;
}
