/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { FieldType } from "./fieldType";

export interface Field {
  /** Unique identifier for the field */
  id: string;
  /** The title of the field */
  title: string;
  /** The type of the field */
  type: FieldType;
  /** List of options (empty for short-text) */
  options: string[];
}
