/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export interface ForgotPasswordResponse {
  /** JWT reset token to be used for password reset */
  token?: string;
}
