/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { FormResponseFieldsItem } from "./formResponseFieldsItem";
import type { FormResponseSettings } from "./formResponseSettings";

export interface FormResponse {
  /** Form ID */
  _id?: string;
  /** ID of the user who created the form */
  createdBy?: string;
  /** Title of the form */
  title?: string;
  /** Description of the form */
  description?: string;
  /** List of allowed domains */
  allowedDomains?: string[];
  /** List of allowed email addresses */
  alowedEmails?: string[];
  /** List of form fields */
  fields?: FormResponseFieldsItem[];
  order?: number;
  settings?: FormResponseSettings;
  /** Status of the form */
  status?: string;
  /** Version key */
  __v?: number;
}
