/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type FormStatus = (typeof FormStatus)[keyof typeof FormStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormStatus = {
  draft: "draft",
  published: "published",
  all: "all",
} as const;
