/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type FormResponseSettings = {
  /** Visibility settings for the form */
  visibility?: string;
  /** Background color in hex format */
  backgroundColor?: string;
  /** Email addresses for notifications */
  emailNotifications?: string[];
};
