/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { FormField } from "./formField";

export interface FormActiveStatusResponse {
  /** Unique form ID */
  _id?: string;
  /** Whether the form is currently active */
  isActive?: boolean;
  fields?: FormField[];
}
