/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

/**
 * Visibility settings for the form
 */
export type FormSettingsVisibility =
  (typeof FormSettingsVisibility)[keyof typeof FormSettingsVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormSettingsVisibility = {
  domain_restricted: "domain_restricted",
  public: "public",
  private: "private",
} as const;
