/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of the form field
 */
export type FormFieldFormFieldType =
  (typeof FormFieldFormFieldType)[keyof typeof FormFieldFormFieldType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormFieldFormFieldType = {
  checkbox: "checkbox",
  radio: "radio",
  select: "select",
  textarea: "textarea",
  text: "text",
} as const;
