/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type FormResponseFieldsItem = {
  /** Field ID */
  _id?: string;
  /** Type of the form field */
  type?: string;
  /** Label for the form field */
  title?: string;
  /** Options for SelectBox type field */
  options?: string[];
  /** Position of the field in the form */
  position?: number;
  /** Whether the field is required */
  required?: boolean;
};
