/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export interface FormSettings {
  visibility?: string;
  backgroundColor?: string;
  headerImage?: string;
  emailNotifications?: string[];
}
