/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { ShortTextResult } from "./shortTextResult";
import type { MultipleChoiceResult } from "./multipleChoiceResult";

export type FormSubmissionResponseResultsItem = ShortTextResult &
  MultipleChoiceResult;
