/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of the form
 */
export type FormRequestStatus =
  (typeof FormRequestStatus)[keyof typeof FormRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormRequestStatus = {
  draft: "draft",
  published: "published",
  archived: "archived",
} as const;
