/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { FormSubmissionResponseResultsItem } from "./formSubmissionResponseResultsItem";
import type { Field } from "./field";
import type { Meta } from "./meta";

export interface FormSubmissionResponse {
  /** List of submission results, varying by field type */
  results: FormSubmissionResponseResultsItem[];
  field: Field;
  meta: Meta;
}
