/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { FormField } from "./formField";
import type { FormSettings } from "./formSettings";
import type { FormStatus } from "./formStatus";

export interface Form {
  _id?: string;
  orgId?: string;
  isActive?: boolean;
  createdBy?: string;
  fields?: FormField[];
  createdAt?: string;
  updatedAt?: string;
  settings?: FormSettings;
  title?: string;
  description?: string;
  status?: FormStatus;
  coverImage?: string;
  logoImage?: string;
  __v?: number;
}
