/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1FormsFormIdVisibility200Visibility } from "./getApiV1FormsFormIdVisibility200Visibility";

export type GetApiV1FormsFormIdVisibility200 = {
  visibility: GetApiV1FormsFormIdVisibility200Visibility;
  allowedEmails: string[];
};
