/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1FormsReceivedStatus } from "./getApiV1FormsReceivedStatus";

export type GetApiV1FormsReceivedParams = {
  /**
   * Filter forms by status (e.g., draft, published)
   */
  status?: GetApiV1FormsReceivedStatus;
  /**
   * Number of forms per page
   */
  limit?: number;
  /**
   * Page number
   */
  page?: number;
  /**
   * Filter forms by active status (true/false)
   */
  isActive?: boolean;
  /**
   * Search forms by title
   */
  title?: string;
  /**
   * Filter forms created after this date (ISO format)
   */
  fromDate?: string;
  /**
   * Filter forms created after this date (ISO format)
   */
  toDate?: string;
};
