/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1FormsSearchStatus } from "./getApiV1FormsSearchStatus";
import type { GetApiV1FormsSearchMode } from "./getApiV1FormsSearchMode";

export type GetApiV1FormsSearchParams = {
  /**
   * Filter forms by status (e.g., draft, published)
   */
  status?: GetApiV1FormsSearchStatus;
  /**
   * Number of forms per page
   */
  limit?: number;
  /**
   * Page number
   */
  page?: number;
  /**
   * Filter forms by active status (true/false)
   */
  isActive?: boolean;
  /**
   * Search forms by title
   */
  title?: string;
  /**
   * Filter forms created after this date (ISO format)
   */
  fromDate?: string;
  /**
   * Filter forms created after this date (ISO format)
   */
  toDate?: string;
  /**
   * mode for sent or draft
   */
  mode?: GetApiV1FormsSearchMode;
};
