/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1FormsSearchStatus =
  (typeof GetApiV1FormsSearchStatus)[keyof typeof GetApiV1FormsSearchStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1FormsSearchStatus = {
  draft: "draft",
  published: "published",
  all: "all",
} as const;
