/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1FormsReceivedMode =
  (typeof GetApiV1FormsReceivedMode)[keyof typeof GetApiV1FormsReceivedMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1FormsReceivedMode = {
  sent: "sent",
} as const;
