/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1SubmissionsSummaryAccessibility =
  (typeof GetApiV1SubmissionsSummaryAccessibility)[keyof typeof GetApiV1SubmissionsSummaryAccessibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1SubmissionsSummaryAccessibility = {
  public: "public",
  private: "private",
} as const;
