/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1FormsSearchMode =
  (typeof GetApiV1FormsSearchMode)[keyof typeof GetApiV1FormsSearchMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1FormsSearchMode = {
  sent: "sent",
} as const;
