/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1FormsReceivedStatus =
  (typeof GetApiV1FormsReceivedStatus)[keyof typeof GetApiV1FormsReceivedStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1FormsReceivedStatus = {
  draft: "draft",
  published: "published",
  all: "all",
} as const;
