/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1SubmissionsSummaryAccessibility } from "./getApiV1SubmissionsSummaryAccessibility";

export type GetApiV1SubmissionsSummaryParams = {
  /**
   * Search submissions by form title
   */
  title?: string;
  /**
   * Filter by accessibility type
   */
  accessibility?: GetApiV1SubmissionsSummaryAccessibility;
};
