/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { Form } from "./form";
import type { PaginationMeta } from "./paginationMeta";

export type GetApiV1FormsSearch200 = {
  docs?: Form[];
  meta?: PaginationMeta;
};
