/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type GetSubmissionsFormFormIdFieldsQuestionParams = {
  /**
   * Page number for pagination
   * @minimum 0
   */
  page: number;
  /**
   * Number of items per page
   * @minimum 1
   */
  limit: number;
};
