/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { EntriesResponse } from "./entriesResponse";
import type { FieldResultsResponse } from "./fieldResultsResponse";

export type GetSubmissionsFormFormIdFieldsQuestion200 =
  | EntriesResponse
  | FieldResultsResponse;
