/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { SubmissionFieldResponse } from "./submissionFieldResponse";
import type { FormField } from "./formField";
import type { FieldMeta } from "./fieldMeta";

export interface GetSubmissionsByFieldResponse {
  submissions?: SubmissionFieldResponse[];
  field?: FormField;
  meta?: FieldMeta;
}
