/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export interface Meta {
  /** Total number of submissions */
  totalSubmissions: number;
  /** Total number of pages */
  totalPages: number;
  /** Current page number */
  page: number;
  /** Number of results per page */
  limit: number;
}
