/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type MultipleChoiceResultUsersItem = {
  /** Unique identifier for the user */
  _id: string;
  /** User's email */
  email: string;
};
