/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { MultipleChoiceResultUsersItem } from "./multipleChoiceResultUsersItem";

export interface MultipleChoiceResult {
  /** The multiple-choice option */
  option: string;
  /** List of users who selected this option */
  users: MultipleChoiceResultUsersItem[];
}
