/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1SubmissionsFormFormId200Data } from "./postApiV1SubmissionsFormFormId200Data";

export type PostApiV1SubmissionsFormFormId200 = {
  data: PostApiV1SubmissionsFormFormId200Data;
};
