/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

/**
 * Dynamic object containing form field IDs as keys and user responses as values
 */
export type PostApiV1SubmissionsFormFormIdBodyData = { [key: string]: string };
