/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";
import type { Tokens } from "./tokens";

export type PostApiV1AuthRegister200 = {
  user?: User;
  tokens?: Tokens;
};
