/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type PutApiV1FormsFormIdUpdateVisibilityBodyVisibilityItem =
  (typeof PutApiV1FormsFormIdUpdateVisibilityBodyVisibilityItem)[keyof typeof PutApiV1FormsFormIdUpdateVisibilityBodyVisibilityItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiV1FormsFormIdUpdateVisibilityBodyVisibilityItem = {
  private: "private",
  public: "public",
  domain_restricted: "domain_restricted",
} as const;
