/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { ReceivedUser } from "./receivedUser";

export interface ReceivedForm {
  _id?: string;
  createdBy?: ReceivedUser;
  title?: string;
  allowedDomains?: string[];
  allowedEmails?: string[];
  status?: string;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
