/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { ReceivedForm } from "./receivedForm";
import type { PaginationMeta } from "./paginationMeta";

export interface ReceivedFormsResponse {
  docs?: ReceivedForm[];
  meta?: PaginationMeta;
}
