/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { ReceivedFormOrg } from "./receivedFormOrg";

export interface ReceivedUser {
  _id?: string;
  username?: string;
  email?: string;
  orgId?: ReceivedFormOrg;
}
