/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export interface Respondent {
  /** Respondent ID */
  _id: string;
  /** Respondent email */
  email: string;
}
