/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export interface SetPasswordRequest {
  email: string;
  newPassword: string;
  /** One-time password used for verification */
  otp: string;
  /** Access token returned from OTP verification */
  accessToken: string;
}
