/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { ShortTextResultAnswerItem } from "./shortTextResultAnswerItem";

export interface ShortTextResult {
  /** Unique identifier for the submission */
  submissionId: string;
  /** Timestamp of when the submission was made */
  submittedAt: string;
  answer?: ShortTextResultAnswerItem[];
}
