/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export type SubmissionAccessibility =
  (typeof SubmissionAccessibility)[keyof typeof SubmissionAccessibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubmissionAccessibility = {
  public: "public",
  private: "private",
} as const;
