/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { SubmissionData } from "./submissionData";
import type { SubmissionAccessibility } from "./submissionAccessibility";

export interface Submission {
  _id?: string;
  formId?: string;
  orgId?: string;
  data?: SubmissionData;
  accessibility?: SubmissionAccessibility;
  submittedBy?: string;
  submittedAt?: string;
  createdAt?: string;
  updatedAt?: string;
  __v?: number;
}
