/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { _SummaryItemId } from "./_summaryItemId";

export interface SummaryItem {
  _id?: _SummaryItemId;
  /** Number of responses received */
  responseCount?: number;
  /** Form ID associated with this summary */
  formId?: string;
  /** Name of the form */
  formName?: string;
}
