/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */
import type { AccessToken } from "./accessToken";
import type { RefreshToken } from "./refreshToken";

export interface Tokens {
  access?: AccessToken;
  refresh?: RefreshToken;
}
