/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Form API
 * API for creating and managing forms
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  _id?: string;
  id?: string;
  email?: string;
  username?: string;
  profileImage?: string;
  orgId?: string;
  isEmailVerified?: boolean;
  roles?: string[];
  __v?: number;
  createdAt?: string;
  updatedAt?: string;
}
